# This is a basic workflow to help you get started with Actions

name: trail_template

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'tests/Test_parameters.txt'
    paths-ignore:
      - 'README.MD'
      - '.github/workflows/**'
      - 'LICENSE.txt'
      - 'CONTRIBUTING.MD'
      - 'AUTHORS.MD'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test trail_template
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      # Check for MATLAB code issues in the project.
      - name: Check for MATLAB code issues
        uses: matlab-actions/run-command@v1
        if: always()
        with:
          command: addpath("buildutil"),RunTest()
          
      #Add files to repository
      - name: Add-files
        if: always()
        continue-on-error: true
        run: |
          git config --global user.email "mikhils@mathworks.com" && git config --global user.name "Mikhil11"
          git add tests/Unittest_results.txt
          git commit -m "test results updated"
          git push
      
      # Publish test results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "report/test_report.xml"
